language: ruby
cache: bundler
rvm:
- 2.1.4
before_script:
- psql -c "CREATE USER base_app WITH PASSWORD 'password1' CREATEDB;" -U postgres
- bundle exec rake db:setup
script:
- bundle exec $TASK
notifications:
  email: false